volumes:
  pg_smartdelivery:

services:
  smartdelivery_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=smartdelivery_db
    volumes:
      - pg_smartdelivery:/var/lib/postgresql/data

    ports:
      - "127.0.0.1:5432:5432"

  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - smartdelivery_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://kitchen_db:5432/smartdelivery_db'
      JAVA_OPTS: '-Xmx512m'